#!/bin/bash

theme=$2

if [ "$1" = "set" ]; then

#polybar
        cp "$HOME/themes/$theme/polybar" "$HOME/.config/polybar/config.ini"
#i3-wm
        cp "$HOME/themes/$theme/i3" "$HOME/.config/i3/config"
#lock screen (https://github.com/Raymo111/i3lock-color)
        cp  "$HOME/themes/$theme/lock" "$HOME/.config/scripts/lock"
#alacritty terminal
	cp "$HOME/themes/$theme/alacritty" "$HOME/.config/alacritty.toml"

elif [ "$1" = "save" ]; then

        mkdir "$HOME/themes/$theme"
#polybar
        cp  "$HOME/.config/polybar/config.ini" "$HOME/themes/$theme/polybar"
#i3-wm
        cp  "$HOME/.config/i3/config" "$HOME/themes/$theme/i3"
#lock screen
        cp  "$HOME/.config/scripts/lock" "$HOME/themes/$theme/lock"
#alacritty terminal
	cp "$HOME/.config/alacritty.toml" "$HOME/themes/$theme/alacritty"

killall polybar

i3-msg restart

fi


#for showing your themes in ~/themes
if [ "$1" = "show" ]; then
	echo Your saved themes:
	ls ~/themes #(change this directory if you're using another one)
fi
