#!/bin/bash

theme=$2

if [ "$1" = "set" ]; then

#polybar
        cp "$HOME/themes/$theme/polybar" "$HOME/.config/polybar/config.ini"
#i3-wm
        cp "$HOME/themes/$theme/i3" "$HOME/.config/i3/config"
#lock screen (https://github.com/Raymo111/i3lock-color)
        cp  "$HOME/themes/$theme/lock" "$HOME/.config/scripts/lock" 

elif [ "$1" = "save" ]; then

        mkdir "$HOME/themes/$theme" 
#polybar
        cp  "$HOME/.config/polybar/config.ini" "$HOME/themes/$theme/polybar"
#i3-wm
        cp  "$HOME/.config/i3/config" "$HOME/themes/$theme/i3"
#lock screen
        cp  "$HOME/.config/scripts/lock" "$HOME/themes/$theme/lock"
fi

killall polybar

polybar &
