#!/bin/bash

#   __ ___________.__                          .____                     .___             __
#  / / \__    ___/|  |__   ____   _____   ____ |    |    _________     __| _/___________  \ \
# / /    |    |   |  |  \_/ __ \ /     \_/ __ \|    |   /  _ \__  \   / __ |/ __ \_  __ \  \ \
# \ \    |    |   |   Y  \  ___/|  Y Y  \  ___/|    |__(  <_> ) __ \_/ /_/ \  ___/|  | \/  / /
#  \_\   |____|   |___|  /\___  >__|_|  /\___  >_______ \____(____  /\____ |\___  >__|    /_/
#                      \/     \/      \/     \/        \/         \/      \/    \/
#
#--feel free to visit my configs on GitHub: https://github.com/AleX-17r/my-system-config

theme=$2
imported="imported"
#Your default themes directory, change this to your own directory.
dir=~/themes

if [ "$1" = "set" ]; then

#polybar
        cp "$dir/$theme/polybar" "$HOME/.config/polybar/config.ini"
#i3-wm
        cp "$dir/$theme/i3" "$HOME/.config/i3/config"
#lock screen (https://github.com/Raymo111/i3lock-color)
        cp  "$dir/$theme/lock" "$HOME/.config/scripts/lock"
#alacritty terminal
	cp "$dir/$theme/alacritty" "$HOME/.config/alacritty.toml"
#if you don't want more than 1 polybar
	killall polybar
	i3-msg restart

elif [ "$1" = "save" ]; then

        mkdir "$dir/$theme"
#polybar
        cp  "$HOME/.config/polybar/config.ini" "$dir/$theme/polybar"
#i3-wm
        cp  "$HOME/.config/i3/config" "$dir/$theme/i3"
#lock screen
        cp  "$HOME/.config/scripts/lock" "$dir/$theme/lock"
#alacritty terminal
	cp "$HOME/.config/alacritty.toml" "$dir/$theme/alacritty"


elif [ "$1" = "remove" ]; then
	echo "removing $theme ..."
	rm -r $dir/$theme
	
elif [ "$1" = "import" ]; then
	#read name
	#mkdir -p $dir/$name
	tar -xzvf $theme -C $dir/
	

elif [ "$1" = "export" ]; then
	echo 'name for this theme?'
	read name
	cd $dir
	tar -czvf "$name".tar.gz $theme


elif [ "$1" = "rename" ]; then
	echo "Type the new name for $theme"
	read newname
	mv /$dir/$theme /$dir/$newname

fi



#for showing your themes in ~/themes (or $dir variable)
if [ "$1" = "show" ]; then
	echo Your saved themes:
	ls $dir #(change this directory if you're using another one)

elif [ "$1" = "help" ]; then
	echo 'This is a simple script for changing and saving themes in i3wm'
	echo 'exec this script continued by:'
	echo '	set    --to set a saved theme'
	echo '	save   --to save a created theme'
	echo '	show   --shows you saved themes'
	echo '	import --allows you to import a created theme'
	echo '	export --allows you to export your saved theme'
	echo '	remove --remove your theme (just rm -r $theme)'
	echo '	rename --rename a saved theme (mv $theme newname)'
	echo '	help   --shows this'
fi
